---
# Proxmox Hypervisor
# IP: 172.19.1.30
# Owner: DNet Team
# Use-case: Proxmox

hostname: pve
management_ip: 172.19.1.30
location: "Core Network"
role: hypervisor

# Credentials (from vault via all.yml)
ansible_user: admin
ansible_password: "{{ admin_password }}"

# Notes
notes: "Proxmox hypervisor"

