---
ansible_host: 172.19.1.24
# CFP Switch
# IP: 172.19.1.24
# Owner: DNET Team
# Use-case: CFP

switch_hostname: sw-cfp
switch_management_ip: 172.19.1.24
switch_location: "CFP Area"
switch_role: special_cfp

# Credentials
ansible_user: admin
# ansible_password: should be in vault

# Switch specific notes
notes: "CFP (Call for Papers) area switch"

