---
ansible_host: 172.19.1.20
# Podium Switch 1
# IP: 172.19.1.20
# Owner: DNET Team
# Use-case: Podium Switch

switch_hostname: sw-pod1
switch_management_ip: 172.19.1.20
switch_location: "Podium 1"
switch_role: podium

# Credentials
ansible_user: admin
# ansible_password: should be in vault

# Switch specific notes
notes: "Podium Switch"

