$ANSIBLE_VAULT;1.1;AES256
62653031376661366363623239376538336638396238636664393163336537323738613538393261
3331366362323239306234363130666263646662393538390a343939393464653032356663663965
33663631646337306335353731663936633637383535393065353062656263333938613934303530
3137666131663964310a326431336664653562383538643532373937313937326365636265356439
63313138386637356130636639346230336464383739623637656131353035613532653565353836
31316537636664383163386466386334303064643933643062393864653932376233623262303439
35316463613139343762663763626537343734653436383532613938653064363639366432656361
66326130636238346163663936393130313339623631373163386462646333636633613734326638
3438
