# Disconet Global Variables
---
# Network settings
disconet:
  domain: disconet.work
  routed_network: 172.19.0.0/16
  dns_servers:
    - 172.19.3.1  # Public services VLAN
    - 1.1.1.1
  ntp_servers:
    - 172.19.3.1  # Public services VLAN
    - time.cloudflare.com
    - pool.ntp.org
  syslog_server: syslog.disconet.work

# Common credentials (sourced from vault.yml)
admin_password: "{{ vault_admin_password }}"
vhid_password: "{{ vault_vhid_password }}"
wap_password: "{{ vault_wap_password }}"
