# Disconet Global Variables
---
# Network settings
disconet:
  domain: disconet.work
  routed_network: 172.19.0.0/16
  dns_servers:
    - 172.19.3.1  # Public services VLAN
    - 1.1.1.1
  ntp_servers:
    - 172.19.3.1  # Public services VLAN
    - time.cloudflare.com
    - pool.ntp.org
  syslog_server: syslog.disconet.work


